### ISSUE TITLE
Thème principal

### ISSUE THREAD

**Issue by T1WiLLi** [T1WiLLi/POTI#2]
## Mettre en place les directives de couleurs principal sous forme de variables CSS

---

## Étapes ou tâches à réaliser ✅
1. [x] Créé un fichier root.css

---

## Résultat attendu 📈

Le fichier devrait contenir les variables suivantes et ces variables devrait être utiliser partout sur le site, sauf exception approuvé. 

```css
:root {
     --primary-color: #000;
     --secondary-color: #000;
     --accent-color: #000;
     --main-font: @font;
     --accent-font: @font;
     --large-title: font_weight;
     --medium-title: font_weight;
     --normal-title: font_weight;
     --large-text: font_weight;
     --medium-text: font_weight;
     --normal-text: font_weight;
     --primary-text-color: #000;
     --secondary-text-color: #000;
     
}
```

---

## Ressources ou informations supplémentaires 📂

Inspirez-vous d'autres site en lignes, ajouter d'autres variables que vous considérer comme globales :)
